
CREATE TABLE ROL_ROL
(
    ROL_ID INT NOT NULL PRIMARY KEY,
    ROL_NOMBRE VARCHAR(60) NOT NULL UNIQUE
)

CREATE TABLE SER_SERVICIO
(
    SER_ID INT NOT NULL PRIMARY KEY,
    SER_NOMBRE VARCHAR (60) NOT NULL,
    SER_DURACION_MIN INT NOT NULL,
    SER_COSTO DECIMAL(10, 2) NOT NULL
)


CREATE TABLE USU_USUARIO
(
    USU_ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
    USU_NOMBRE VARCHAR(100) NOT NULL,
    USU_APELLIDO VARCHAR(100) NOT NULL, 
    USU_EMAIL VARCHAR(100) NOT NULL UNIQUE, 
    USU_CLAVE VARCHAR(255) NOT NULL, 
    USU_ROL_ID INT NOT NULL,
    FOREIGN KEY(USU_ROL_ID) REFERENCES ROL_ROL(ROL_ID)
)


CREATE TABLE CLI_CLIENTE
(
    CLI_ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
    CLI_NOMBRE VARCHAR(100) NOT NULL, 
    CLI_APELLIDO VARCHAR(100) NOT NULL, 
    CLI_RUT VARCHAR (20) NOT NULL UNIQUE, 
    CLI_EMAIL VARCHAR (100) NOT NULL,
    CLI_FONO VARCHAR(20) NOT NULL 
)


CREATE TABLE CIT_CITA
(
    CIT_ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
    CIT_CLI_ID INT NOT NULL,
    CIT_USU_ID_PROFESIONAL INT NOT NULL,
    CIT_SER_ID INT NOT NULL,
    CIT_FECHA_HORA_INICIO DATETIME NOT NULL,
    CIT_FECHA_HORA_FIN DATETIME NOT NULL,
    CIT_ESTADO VARCHAR(50) NOT NULL CHECK (CIT_ESTADO IN ('Pendiente', 'Confirmada', 'Cancelada', 'Realizada')),
    FOREIGN KEY (CIT_CLI_ID) REFERENCES CLI_CLIENTE(CLI_ID),
    FOREIGN KEY (CIT_USU_ID_PROFESIONAL) REFERENCES USU_USUARIO(USU_ID),
    FOREIGN KEY (CIT_SER_ID) REFERENCES SER_SERVICIO(SER_ID),
    CONSTRAINT CK_CITA_DURACION CHECK (CIT_FECHA_HORA_FIN > CIT_FECHA_HORA_INICIO)
)


CREATE TABLE HIS_HISTORIAL
(
    HIS_ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
    HIS_CLI_ID INT NOT NULL,
    HIS_USU_ID_PROFESIONAL INT NOT NULL,
    HIS_FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    HIS_DIAGNOSTICO TEXT,
    HIS_TRATAMIENTO_APLICADO TEXT,
    HIS_FOTO_URL VARCHAR(255), 
    HIS_CIT_ID INT, 
    
    FOREIGN KEY (HIS_CLI_ID) REFERENCES CLI_CLIENTE(CLI_ID),
    FOREIGN KEY (HIS_USU_ID_PROFESIONAL) REFERENCES USU_USUARIO(USU_ID),
    FOREIGN KEY (HIS_CIT_ID) REFERENCES CIT_CITA(CIT_ID)
)
INSERT INTO ROL_ROL (ROL_ID, ROL_NOMBRE) VALUES (1, 'Administrador');
INSERT INTO ROL_ROL (ROL_ID, ROL_NOMBRE) VALUES (2, 'Esteticista');
INSERT INTO ROL_ROL (ROL_ID, ROL_NOMBRE) VALUES (3, 'Dermat�logo');

