CREATE TABLE ROL_ROL
(
    ROL_ID INT NOT NULL PRIMARY KEY,
    ROL_NOMBRE VARCHAR(60) NOT NULL UNIQUE
)


CREATE TABLE SER_SERVICIO
(
    SER_ID INT NOT NULL PRIMARY KEY,
    SER_NOMBRE VARCHAR (60) NOT NULL,
    SER_DURACION_MIN INT NOT NULL,
    SER_COSTO DECIMAL(10, 2) NOT NULL
)



CREATE TABLE USU_USUARIO
(
    USU_ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
    USU_NOMBRE VARCHAR(100) NOT NULL,
    USU_APELLIDO VARCHAR(100) NOT NULL, 
    USU_EMAIL VARCHAR(100) NOT NULL UNIQUE, 
    USU_CLAVE VARCHAR(255) NOT NULL, 
    USU_ROL_ID INT NOT NULL,
    FOREIGN KEY(USU_ROL_ID) REFERENCES ROL_ROL(ROL_ID)
)


CREATE TABLE CLI_CLIENTE
(
    CLI_ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
    CLI_NOMBRE VARCHAR(100) NOT NULL, 
    CLI_APELLIDO VARCHAR(100) NOT NULL, 
    CLI_RUT VARCHAR (20) NOT NULL UNIQUE, 
    CLI_EMAIL VARCHAR (100) NOT NULL,
    CLI_FONO VARCHAR(20) NOT NULL 
)


CREATE TABLE CIT_CITA
(
    CIT_ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
    CIT_CLI_ID INT NOT NULL,
    CIT_USU_ID_PROFESIONAL INT NOT NULL,
    CIT_SER_ID INT NOT NULL,
    CIT_FECHA_HORA_INICIO DATETIME NOT NULL,
    CIT_FECHA_HORA_FIN DATETIME NOT NULL,
    CIT_ESTADO VARCHAR(50) NOT NULL CHECK (CIT_ESTADO IN ('Pendiente', 'Confirmada', 'Cancelada', 'Realizada')),
    FOREIGN KEY (CIT_CLI_ID) REFERENCES CLI_CLIENTE(CLI_ID),
    FOREIGN KEY (CIT_USU_ID_PROFESIONAL) REFERENCES USU_USUARIO(USU_ID),
    FOREIGN KEY (CIT_SER_ID) REFERENCES SER_SERVICIO(SER_ID),
    CONSTRAINT CK_CITA_DURACION CHECK (CIT_FECHA_HORA_FIN > CIT_FECHA_HORA_INICIO)
)


CREATE TABLE HIS_HISTORIAL
(
    HIS_ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
    HIS_CLI_ID INT NOT NULL,
    HIS_USU_ID_PROFESIONAL INT NOT NULL,
    HIS_FECHA_REGISTRO DATETIME DEFAULT GETDATE(),
    HIS_DIAGNOSTICO TEXT,
    HIS_TRATAMIENTO_APLICADO TEXT,
    HIS_FOTO_URL VARCHAR(255), 
    HIS_CIT_ID INT, 
    
    FOREIGN KEY (HIS_CLI_ID) REFERENCES CLI_CLIENTE(CLI_ID),
    FOREIGN KEY (HIS_USU_ID_PROFESIONAL) REFERENCES USU_USUARIO(USU_ID),
    FOREIGN KEY (HIS_CIT_ID) REFERENCES CIT_CITA(CIT_ID)
)
---insertar roles
INSERT INTO ROL_ROL (ROL_ID, ROL_NOMBRE) VALUES (1, 'Administrador');
INSERT INTO ROL_ROL (ROL_ID, ROL_NOMBRE) VALUES (2, 'Esteticista');
INSERT INTO ROL_ROL (ROL_ID, ROL_NOMBRE) VALUES (3, 'Dermatólogo');

select * from USU_USUARIO
select * from ROL_ROL

DELETE FROM USU_USUARIO;


CREATE PROCEDURE CONSULTARCITASACTIVAS
    @UsuarioID INT,
    @RolID INT
AS
BEGIN
    SET NOCOUNT ON;
    
    DECLARE @AdminRolID INT = 1; 

    SELECT
        CIT_CITA.CIT_ID AS CitaID,
        CIT_CITA.CIT_FECHA_HORA_INICIO AS FechaCita,
        CIT_CITA.CIT_FECHA_HORA_FIN AS HoraCita,
        SER_SERVICIO.SER_NOMBRE AS NombreServicio,
        CIT_CITA.CIT_ESTADO AS Estado,
        CLI_CLIENTE.CLI_NOMBRE + ' ' + CLI_CLIENTE.CLI_APELLIDO AS NombreCliente
    FROM
        CIT_CITA 
    INNER JOIN 
        SER_SERVICIO ON CIT_CITA.CIT_SER_ID = SER_SERVICIO.SER_ID
    INNER JOIN
        CLI_CLIENTE ON CIT_CITA.CIT_CLI_ID = CLI_CLIENTE.CLI_ID
    WHERE
        (
            @RolID = @AdminRolID 
            OR 
            CIT_CITA.CIT_USU_ID_PROFESIONAL = @UsuarioID
        )
        AND CIT_CITA.CIT_ESTADO IN ('Pendiente', 'Confirmada')
    ORDER BY
        CIT_CITA.CIT_FECHA_HORA_INICIO ASC;
END



EXEC CREARCUENTA 
    @Nombre = 'Juan', 
    @Apellido = 'P?rez', 
    @Email = 'juan.perez@email.com', 
    @Clave = 'claveSecretaHash123', 
    @RolID = 1;
end
//* Procedimiento para AUTENTIFICACION
CREATE PROCEDURE AUTENTIFICACION
@USER VARCHAR (60),
@CLAVE VARCHAR (60)
AS
BEGIN
	SELECT
		*
		FROM
		USU_USUARIO
		WHERE
		USU_USER=@USER AND
		USU_CLAVE=@CLAVE

END
*//

CREATE PROCEDURE OBTENERUSUARIO
    @Email VARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT USU_ID, USU_NOMBRE, USU_APELLIDO, USU_CLAVE, USU_ROL_ID
    FROM dbo.USU_USUARIO
    WHERE USU_EMAIL = @Email;
END